package bo;

import java.util.Date;

/**
 * GpExpResume generated by MyEclipse Persistence Tools
 */

public class GpExpResume extends GpGcjsTbr{

	// Fields

	private String expId;

	private String fullname;

	private Date birthday;

	private String idcard;

	private String company;

	private String specNow;

	private String specRank;

	private Date rankDate;

	private String school;

	private String mobileNo;

	private String officeAddr;

	private String officeTel;

	private String email;

	private String officePostcode;

	private String region;

	private String sex;

	private String politics;

	private String position;

	private String schoolResume;

	private String schoolSpec;

	private String attend;

	private String typeMajor;

	private String typeMajorCnt;

	private String typeSecond;

	private String typeSecondCnt;

	private String mome;

	private String shun;

	private Date engageDate;

	private String engageUnit;

	private String expStatus;

	private String specialty;

	private String expType;

	private String yhid;

	private String source;

	private String telCode;

	private String userStatus;

	private String degreeCode;

	private String huibiids;

	private String areaId;

	private String expCardNo;

	private String totalExpType;

	private String depType;

	private String totalScore;

	private String ywlx;

	private Long seqId;
	
	public String aaaa;

	// Constructors

	/** default constructor */
	public GpExpResume() {
	}

	/** minimal constructor */
	public GpExpResume(String expId) {
		this.expId = expId;
	}

	/** full constructor */
	public GpExpResume(String expId, String fullname, Date birthday,
			String idcard, String company, String specNow, String specRank,
			Date rankDate, String school, String mobileNo, String officeAddr,
			String officeTel, String email, String officePostcode,
			String region, String sex, String politics, String position,
			String schoolResume, String schoolSpec, String attend,
			String typeMajor, String typeMajorCnt, String typeSecond,
			String typeSecondCnt, String mome, String shun, Date engageDate,
			String engageUnit, String expStatus, String specialty,
			String expType, String yhid, String source, String telCode,
			String userStatus, String degreeCode, String huibiids,
			String areaId, String expCardNo, String totalExpType,
			String depType, String totalScore, String ywlx, Long seqId) {
		this.expId = expId;
		this.fullname = fullname;
		this.birthday = birthday;
		this.idcard = idcard;
		this.company = company;
		this.specNow = specNow;
		this.specRank = specRank;
		this.rankDate = rankDate;
		this.school = school;
		this.mobileNo = mobileNo;
		this.officeAddr = officeAddr;
		this.officeTel = officeTel;
		this.email = email;
		this.officePostcode = officePostcode;
		this.region = region;
		this.sex = sex;
		this.politics = politics;
		this.position = position;
		this.schoolResume = schoolResume;
		this.schoolSpec = schoolSpec;
		this.attend = attend;
		this.typeMajor = typeMajor;
		this.typeMajorCnt = typeMajorCnt;
		this.typeSecond = typeSecond;
		this.typeSecondCnt = typeSecondCnt;
		this.mome = mome;
		this.shun = shun;
		this.engageDate = engageDate;
		this.engageUnit = engageUnit;
		this.expStatus = expStatus;
		this.specialty = specialty;
		this.expType = expType;
		this.yhid = yhid;
		this.source = source;
		this.telCode = telCode;
		this.userStatus = userStatus;
		this.degreeCode = degreeCode;
		this.huibiids = huibiids;
		this.areaId = areaId;
		this.expCardNo = expCardNo;
		this.totalExpType = totalExpType;
		this.depType = depType;
		this.totalScore = totalScore;
		this.ywlx = ywlx;
		this.seqId = seqId;
	}

	// Property accessors

	public String getExpId() {
		return this.expId;
	}

	public void setExpId(String expId) {
		this.expId = expId;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getIdcard() {
		return this.idcard;
	}

	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getSpecNow() {
		return this.specNow;
	}

	public void setSpecNow(String specNow) {
		this.specNow = specNow;
	}

	public String getSpecRank() {
		return this.specRank;
	}

	public void setSpecRank(String specRank) {
		this.specRank = specRank;
	}

	public Date getRankDate() {
		return this.rankDate;
	}

	public void setRankDate(Date rankDate) {
		this.rankDate = rankDate;
	}

	public String getSchool() {
		return this.school;
	}

	public void setSchool(String school) {
		this.school = school;
	}

	public String getMobileNo() {
		return this.mobileNo;
	}

	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}

	public String getOfficeAddr() {
		return this.officeAddr;
	}

	public void setOfficeAddr(String officeAddr) {
		this.officeAddr = officeAddr;
	}

	public String getOfficeTel() {
		return this.officeTel;
	}

	public void setOfficeTel(String officeTel) {
		this.officeTel = officeTel;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getOfficePostcode() {
		return this.officePostcode;
	}

	public void setOfficePostcode(String officePostcode) {
		this.officePostcode = officePostcode;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPolitics() {
		return this.politics;
	}

	public void setPolitics(String politics) {
		this.politics = politics;
	}

	public String getPosition() {
		return this.position;
	}

	public void setPosition(String position) {
		this.position = position;
	}

	public String getSchoolResume() {
		return this.schoolResume;
	}

	public void setSchoolResume(String schoolResume) {
		this.schoolResume = schoolResume;
	}

	public String getSchoolSpec() {
		return this.schoolSpec;
	}

	public void setSchoolSpec(String schoolSpec) {
		this.schoolSpec = schoolSpec;
	}

	public String getAttend() {
		return this.attend;
	}

	public void setAttend(String attend) {
		this.attend = attend;
	}

	public String getTypeMajor() {
		return this.typeMajor;
	}

	public void setTypeMajor(String typeMajor) {
		this.typeMajor = typeMajor;
	}

	public String getTypeMajorCnt() {
		return this.typeMajorCnt;
	}

	public void setTypeMajorCnt(String typeMajorCnt) {
		this.typeMajorCnt = typeMajorCnt;
	}

	public String getTypeSecond() {
		return this.typeSecond;
	}

	public void setTypeSecond(String typeSecond) {
		this.typeSecond = typeSecond;
	}

	public String getTypeSecondCnt() {
		return this.typeSecondCnt;
	}

	public void setTypeSecondCnt(String typeSecondCnt) {
		this.typeSecondCnt = typeSecondCnt;
	}

	public String getMome() {
		return this.mome;
	}

	public void setMome(String mome) {
		this.mome = mome;
	}

	public String getShun() {
		return this.shun;
	}

	public void setShun(String shun) {
		this.shun = shun;
	}

	public Date getEngageDate() {
		return this.engageDate;
	}

	public void setEngageDate(Date engageDate) {
		this.engageDate = engageDate;
	}

	public String getEngageUnit() {
		return this.engageUnit;
	}

	public void setEngageUnit(String engageUnit) {
		this.engageUnit = engageUnit;
	}

	public String getExpStatus() {
		return this.expStatus;
	}

	public void setExpStatus(String expStatus) {
		this.expStatus = expStatus;
	}

	public String getSpecialty() {
		return this.specialty;
	}

	public void setSpecialty(String specialty) {
		this.specialty = specialty;
	}

	public String getExpType() {
		return this.expType;
	}

	public void setExpType(String expType) {
		this.expType = expType;
	}

	public String getYhid() {
		return this.yhid;
	}

	public void setYhid(String yhid) {
		this.yhid = yhid;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getTelCode() {
		return this.telCode;
	}

	public void setTelCode(String telCode) {
		this.telCode = telCode;
	}

	public String getUserStatus() {
		return this.userStatus;
	}

	public void setUserStatus(String userStatus) {
		this.userStatus = userStatus;
	}

	public String getDegreeCode() {
		return this.degreeCode;
	}

	public void setDegreeCode(String degreeCode) {
		this.degreeCode = degreeCode;
	}

	public String getHuibiids() {
		return this.huibiids;
	}

	public void setHuibiids(String huibiids) {
		this.huibiids = huibiids;
	}

	public String getAreaId() {
		return this.areaId;
	}

	public void setAreaId(String areaId) {
		this.areaId = areaId;
	}

	public String getExpCardNo() {
		return this.expCardNo;
	}

	public void setExpCardNo(String expCardNo) {
		this.expCardNo = expCardNo;
	}

	public String getTotalExpType() {
		return this.totalExpType;
	}

	public void setTotalExpType(String totalExpType) {
		this.totalExpType = totalExpType;
	}

	public String getDepType() {
		return this.depType;
	}

	public void setDepType(String depType) {
		this.depType = depType;
	}

	public String getTotalScore() {
		return this.totalScore;
	}

	public void setTotalScore(String totalScore) {
		this.totalScore = totalScore;
	}

	public String getYwlx() {
		return this.ywlx;
	}

	public void setYwlx(String ywlx) {
		this.ywlx = ywlx;
	}

	public Long getSeqId() {
		return this.seqId;
	}

	public void setSeqId(Long seqId) {
		this.seqId = seqId;
	}

	public String getAaaa() {
		return aaaa;
	}

	public void setAaaa(String aaaa) {
		this.aaaa = aaaa;
	}

}