package bo;

import java.util.Date;

/**
 * GpGcjsTbrId generated by MyEclipse Persistence Tools
 */

public class GpGcjsTbrId implements java.io.Serializable {

	// Fields

	private String id;

	private String tbrName;

	private String jyCode;

	private String qyzz;

	private String depCode;

	private String aqxkzbh;

	private String frdb;

	private String frZzCode;

	private String qyfzr;

	private String fzrZzCode;

	private String jsfzr;

	private String jsfzrZzCode;

	private String aqscfjl;

	private String fjlZzCode;

	private String jgdm;

	private String qyType;

	private String qyQuality;

	private String qyYyzzh;

	private String scxkz;

	private Date xkzDate;

	private String bank;

	private String bankNo;

	private Double zcMoney;

	private String qyLinkman;

	private String qyLinkphone;

	private String qyFax;

	private String qyAddr;

	// Constructors

	/** default constructor */
	public GpGcjsTbrId() {
	}

	/** minimal constructor */
	public GpGcjsTbrId(String id) {
		this.id = id;
	}

	/** full constructor */
	public GpGcjsTbrId(String id, String tbrName, String jyCode, String qyzz,
			String depCode, String aqxkzbh, String frdb, String frZzCode,
			String qyfzr, String fzrZzCode, String jsfzr, String jsfzrZzCode,
			String aqscfjl, String fjlZzCode, String jgdm, String qyType,
			String qyQuality, String qyYyzzh, String scxkz, Date xkzDate,
			String bank, String bankNo, Double zcMoney, String qyLinkman,
			String qyLinkphone, String qyFax, String qyAddr) {
		this.id = id;
		this.tbrName = tbrName;
		this.jyCode = jyCode;
		this.qyzz = qyzz;
		this.depCode = depCode;
		this.aqxkzbh = aqxkzbh;
		this.frdb = frdb;
		this.frZzCode = frZzCode;
		this.qyfzr = qyfzr;
		this.fzrZzCode = fzrZzCode;
		this.jsfzr = jsfzr;
		this.jsfzrZzCode = jsfzrZzCode;
		this.aqscfjl = aqscfjl;
		this.fjlZzCode = fjlZzCode;
		this.jgdm = jgdm;
		this.qyType = qyType;
		this.qyQuality = qyQuality;
		this.qyYyzzh = qyYyzzh;
		this.scxkz = scxkz;
		this.xkzDate = xkzDate;
		this.bank = bank;
		this.bankNo = bankNo;
		this.zcMoney = zcMoney;
		this.qyLinkman = qyLinkman;
		this.qyLinkphone = qyLinkphone;
		this.qyFax = qyFax;
		this.qyAddr = qyAddr;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getTbrName() {
		return this.tbrName;
	}

	public void setTbrName(String tbrName) {
		this.tbrName = tbrName;
	}

	public String getJyCode() {
		return this.jyCode;
	}

	public void setJyCode(String jyCode) {
		this.jyCode = jyCode;
	}

	public String getQyzz() {
		return this.qyzz;
	}

	public void setQyzz(String qyzz) {
		this.qyzz = qyzz;
	}

	public String getDepCode() {
		return this.depCode;
	}

	public void setDepCode(String depCode) {
		this.depCode = depCode;
	}

	public String getAqxkzbh() {
		return this.aqxkzbh;
	}

	public void setAqxkzbh(String aqxkzbh) {
		this.aqxkzbh = aqxkzbh;
	}

	public String getFrdb() {
		return this.frdb;
	}

	public void setFrdb(String frdb) {
		this.frdb = frdb;
	}

	public String getFrZzCode() {
		return this.frZzCode;
	}

	public void setFrZzCode(String frZzCode) {
		this.frZzCode = frZzCode;
	}

	public String getQyfzr() {
		return this.qyfzr;
	}

	public void setQyfzr(String qyfzr) {
		this.qyfzr = qyfzr;
	}

	public String getFzrZzCode() {
		return this.fzrZzCode;
	}

	public void setFzrZzCode(String fzrZzCode) {
		this.fzrZzCode = fzrZzCode;
	}

	public String getJsfzr() {
		return this.jsfzr;
	}

	public void setJsfzr(String jsfzr) {
		this.jsfzr = jsfzr;
	}

	public String getJsfzrZzCode() {
		return this.jsfzrZzCode;
	}

	public void setJsfzrZzCode(String jsfzrZzCode) {
		this.jsfzrZzCode = jsfzrZzCode;
	}

	public String getAqscfjl() {
		return this.aqscfjl;
	}

	public void setAqscfjl(String aqscfjl) {
		this.aqscfjl = aqscfjl;
	}

	public String getFjlZzCode() {
		return this.fjlZzCode;
	}

	public void setFjlZzCode(String fjlZzCode) {
		this.fjlZzCode = fjlZzCode;
	}

	public String getJgdm() {
		return this.jgdm;
	}

	public void setJgdm(String jgdm) {
		this.jgdm = jgdm;
	}

	public String getQyType() {
		return this.qyType;
	}

	public void setQyType(String qyType) {
		this.qyType = qyType;
	}

	public String getQyQuality() {
		return this.qyQuality;
	}

	public void setQyQuality(String qyQuality) {
		this.qyQuality = qyQuality;
	}

	public String getQyYyzzh() {
		return this.qyYyzzh;
	}

	public void setQyYyzzh(String qyYyzzh) {
		this.qyYyzzh = qyYyzzh;
	}

	public String getScxkz() {
		return this.scxkz;
	}

	public void setScxkz(String scxkz) {
		this.scxkz = scxkz;
	}

	public Date getXkzDate() {
		return this.xkzDate;
	}

	public void setXkzDate(Date xkzDate) {
		this.xkzDate = xkzDate;
	}

	public String getBank() {
		return this.bank;
	}

	public void setBank(String bank) {
		this.bank = bank;
	}

	public String getBankNo() {
		return this.bankNo;
	}

	public void setBankNo(String bankNo) {
		this.bankNo = bankNo;
	}

	public Double getZcMoney() {
		return this.zcMoney;
	}

	public void setZcMoney(Double zcMoney) {
		this.zcMoney = zcMoney;
	}

	public String getQyLinkman() {
		return this.qyLinkman;
	}

	public void setQyLinkman(String qyLinkman) {
		this.qyLinkman = qyLinkman;
	}

	public String getQyLinkphone() {
		return this.qyLinkphone;
	}

	public void setQyLinkphone(String qyLinkphone) {
		this.qyLinkphone = qyLinkphone;
	}

	public String getQyFax() {
		return this.qyFax;
	}

	public void setQyFax(String qyFax) {
		this.qyFax = qyFax;
	}

	public String getQyAddr() {
		return this.qyAddr;
	}

	public void setQyAddr(String qyAddr) {
		this.qyAddr = qyAddr;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GpGcjsTbrId))
			return false;
		GpGcjsTbrId castOther = (GpGcjsTbrId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getTbrName() == castOther.getTbrName()) || (this
						.getTbrName() != null
						&& castOther.getTbrName() != null && this.getTbrName()
						.equals(castOther.getTbrName())))
				&& ((this.getJyCode() == castOther.getJyCode()) || (this
						.getJyCode() != null
						&& castOther.getJyCode() != null && this.getJyCode()
						.equals(castOther.getJyCode())))
				&& ((this.getQyzz() == castOther.getQyzz()) || (this.getQyzz() != null
						&& castOther.getQyzz() != null && this.getQyzz()
						.equals(castOther.getQyzz())))
				&& ((this.getDepCode() == castOther.getDepCode()) || (this
						.getDepCode() != null
						&& castOther.getDepCode() != null && this.getDepCode()
						.equals(castOther.getDepCode())))
				&& ((this.getAqxkzbh() == castOther.getAqxkzbh()) || (this
						.getAqxkzbh() != null
						&& castOther.getAqxkzbh() != null && this.getAqxkzbh()
						.equals(castOther.getAqxkzbh())))
				&& ((this.getFrdb() == castOther.getFrdb()) || (this.getFrdb() != null
						&& castOther.getFrdb() != null && this.getFrdb()
						.equals(castOther.getFrdb())))
				&& ((this.getFrZzCode() == castOther.getFrZzCode()) || (this
						.getFrZzCode() != null
						&& castOther.getFrZzCode() != null && this
						.getFrZzCode().equals(castOther.getFrZzCode())))
				&& ((this.getQyfzr() == castOther.getQyfzr()) || (this
						.getQyfzr() != null
						&& castOther.getQyfzr() != null && this.getQyfzr()
						.equals(castOther.getQyfzr())))
				&& ((this.getFzrZzCode() == castOther.getFzrZzCode()) || (this
						.getFzrZzCode() != null
						&& castOther.getFzrZzCode() != null && this
						.getFzrZzCode().equals(castOther.getFzrZzCode())))
				&& ((this.getJsfzr() == castOther.getJsfzr()) || (this
						.getJsfzr() != null
						&& castOther.getJsfzr() != null && this.getJsfzr()
						.equals(castOther.getJsfzr())))
				&& ((this.getJsfzrZzCode() == castOther.getJsfzrZzCode()) || (this
						.getJsfzrZzCode() != null
						&& castOther.getJsfzrZzCode() != null && this
						.getJsfzrZzCode().equals(castOther.getJsfzrZzCode())))
				&& ((this.getAqscfjl() == castOther.getAqscfjl()) || (this
						.getAqscfjl() != null
						&& castOther.getAqscfjl() != null && this.getAqscfjl()
						.equals(castOther.getAqscfjl())))
				&& ((this.getFjlZzCode() == castOther.getFjlZzCode()) || (this
						.getFjlZzCode() != null
						&& castOther.getFjlZzCode() != null && this
						.getFjlZzCode().equals(castOther.getFjlZzCode())))
				&& ((this.getJgdm() == castOther.getJgdm()) || (this.getJgdm() != null
						&& castOther.getJgdm() != null && this.getJgdm()
						.equals(castOther.getJgdm())))
				&& ((this.getQyType() == castOther.getQyType()) || (this
						.getQyType() != null
						&& castOther.getQyType() != null && this.getQyType()
						.equals(castOther.getQyType())))
				&& ((this.getQyQuality() == castOther.getQyQuality()) || (this
						.getQyQuality() != null
						&& castOther.getQyQuality() != null && this
						.getQyQuality().equals(castOther.getQyQuality())))
				&& ((this.getQyYyzzh() == castOther.getQyYyzzh()) || (this
						.getQyYyzzh() != null
						&& castOther.getQyYyzzh() != null && this.getQyYyzzh()
						.equals(castOther.getQyYyzzh())))
				&& ((this.getScxkz() == castOther.getScxkz()) || (this
						.getScxkz() != null
						&& castOther.getScxkz() != null && this.getScxkz()
						.equals(castOther.getScxkz())))
				&& ((this.getXkzDate() == castOther.getXkzDate()) || (this
						.getXkzDate() != null
						&& castOther.getXkzDate() != null && this.getXkzDate()
						.equals(castOther.getXkzDate())))
				&& ((this.getBank() == castOther.getBank()) || (this.getBank() != null
						&& castOther.getBank() != null && this.getBank()
						.equals(castOther.getBank())))
				&& ((this.getBankNo() == castOther.getBankNo()) || (this
						.getBankNo() != null
						&& castOther.getBankNo() != null && this.getBankNo()
						.equals(castOther.getBankNo())))
				&& ((this.getZcMoney() == castOther.getZcMoney()) || (this
						.getZcMoney() != null
						&& castOther.getZcMoney() != null && this.getZcMoney()
						.equals(castOther.getZcMoney())))
				&& ((this.getQyLinkman() == castOther.getQyLinkman()) || (this
						.getQyLinkman() != null
						&& castOther.getQyLinkman() != null && this
						.getQyLinkman().equals(castOther.getQyLinkman())))
				&& ((this.getQyLinkphone() == castOther.getQyLinkphone()) || (this
						.getQyLinkphone() != null
						&& castOther.getQyLinkphone() != null && this
						.getQyLinkphone().equals(castOther.getQyLinkphone())))
				&& ((this.getQyFax() == castOther.getQyFax()) || (this
						.getQyFax() != null
						&& castOther.getQyFax() != null && this.getQyFax()
						.equals(castOther.getQyFax())))
				&& ((this.getQyAddr() == castOther.getQyAddr()) || (this
						.getQyAddr() != null
						&& castOther.getQyAddr() != null && this.getQyAddr()
						.equals(castOther.getQyAddr())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getTbrName() == null ? 0 : this.getTbrName().hashCode());
		result = 37 * result
				+ (getJyCode() == null ? 0 : this.getJyCode().hashCode());
		result = 37 * result
				+ (getQyzz() == null ? 0 : this.getQyzz().hashCode());
		result = 37 * result
				+ (getDepCode() == null ? 0 : this.getDepCode().hashCode());
		result = 37 * result
				+ (getAqxkzbh() == null ? 0 : this.getAqxkzbh().hashCode());
		result = 37 * result
				+ (getFrdb() == null ? 0 : this.getFrdb().hashCode());
		result = 37 * result
				+ (getFrZzCode() == null ? 0 : this.getFrZzCode().hashCode());
		result = 37 * result
				+ (getQyfzr() == null ? 0 : this.getQyfzr().hashCode());
		result = 37 * result
				+ (getFzrZzCode() == null ? 0 : this.getFzrZzCode().hashCode());
		result = 37 * result
				+ (getJsfzr() == null ? 0 : this.getJsfzr().hashCode());
		result = 37
				* result
				+ (getJsfzrZzCode() == null ? 0 : this.getJsfzrZzCode()
						.hashCode());
		result = 37 * result
				+ (getAqscfjl() == null ? 0 : this.getAqscfjl().hashCode());
		result = 37 * result
				+ (getFjlZzCode() == null ? 0 : this.getFjlZzCode().hashCode());
		result = 37 * result
				+ (getJgdm() == null ? 0 : this.getJgdm().hashCode());
		result = 37 * result
				+ (getQyType() == null ? 0 : this.getQyType().hashCode());
		result = 37 * result
				+ (getQyQuality() == null ? 0 : this.getQyQuality().hashCode());
		result = 37 * result
				+ (getQyYyzzh() == null ? 0 : this.getQyYyzzh().hashCode());
		result = 37 * result
				+ (getScxkz() == null ? 0 : this.getScxkz().hashCode());
		result = 37 * result
				+ (getXkzDate() == null ? 0 : this.getXkzDate().hashCode());
		result = 37 * result
				+ (getBank() == null ? 0 : this.getBank().hashCode());
		result = 37 * result
				+ (getBankNo() == null ? 0 : this.getBankNo().hashCode());
		result = 37 * result
				+ (getZcMoney() == null ? 0 : this.getZcMoney().hashCode());
		result = 37 * result
				+ (getQyLinkman() == null ? 0 : this.getQyLinkman().hashCode());
		result = 37
				* result
				+ (getQyLinkphone() == null ? 0 : this.getQyLinkphone()
						.hashCode());
		result = 37 * result
				+ (getQyFax() == null ? 0 : this.getQyFax().hashCode());
		result = 37 * result
				+ (getQyAddr() == null ? 0 : this.getQyAddr().hashCode());
		return result;
	}

}