package bo;

/**
 * GpGcjsTbrZz generated by MyEclipse Persistence Tools
 */

public class GpGcjsTbrZz implements java.io.Serializable {

	// Fields

	private GpGcjsTbrZzId id;

	// Constructors

	/** default constructor */
	public GpGcjsTbrZz() {
	}

	/** full constructor */
	public GpGcjsTbrZz(GpGcjsTbrZzId id) {
		this.id = id;
	}

	// Property accessors

	public GpGcjsTbrZzId getId() {
		return this.id;
	}

	public void setId(GpGcjsTbrZzId id) {
		this.id = id;
	}

}