package bo;

/**
 * GpGcjsTbr generated by MyEclipse Persistence Tools
 */

public class GpGcjsTbr implements java.io.Serializable {

	// Fields

	private GpGcjsTbrId id;

	// Constructors

	/** default constructor */
	public GpGcjsTbr() {
	}

	/** full constructor */
	public GpGcjsTbr(GpGcjsTbrId id) {
		this.id = id;
	}

	// Property accessors

	public GpGcjsTbrId getId() {
		return this.id;
	}

	public void setId(GpGcjsTbrId id) {
		this.id = id;
	}

}