package bo;

/**
 * GpGcjsXmjl generated by MyEclipse Persistence Tools
 */

public class GpGcjsXmjl implements java.io.Serializable {

	// Fields

	private GpGcjsXmjlId id;

	// Constructors

	/** default constructor */
	public GpGcjsXmjl() {
	}

	/** full constructor */
	public GpGcjsXmjl(GpGcjsXmjlId id) {
		this.id = id;
	}

	// Property accessors

	public GpGcjsXmjlId getId() {
		return this.id;
	}

	public void setId(GpGcjsXmjlId id) {
		this.id = id;
	}

}