package bo;

/**
 * GpGcjsTbr generated by MyEclipse Persistence Tools
 */

public class GpGcjsTbr implements java.io.Serializable {

	// Fields

	private GpGcjsTbrId id;
	
	public String aaaaaaa;

	// Constructors

	/** default constructor */
	public GpGcjsTbr() {
	}

	public String getAaaaaaa() {
		return aaaaaaa;
	}

	public void setAaaaaaa(String aaaaaaa) {
		this.aaaaaaa = aaaaaaa;
	}

	/** full constructor */
	public GpGcjsTbr(GpGcjsTbrId id) {
		this.id = id;
	}

	// Property accessors

	public GpGcjsTbrId getId() {
		return this.id;
	}

	public void setId(GpGcjsTbrId id) {
		this.id = id;
	}

}