package bo;

/**
 * GpGcjsXmjlId generated by MyEclipse Persistence Tools
 */

public class GpGcjsXmjlId implements java.io.Serializable {

	// Fields

	private String id;

	private String name;

	private String phone;

	private String zzName;

	private String zzCode;

	private String note;

	// Constructors

	/** default constructor */
	public GpGcjsXmjlId() {
	}

	/** minimal constructor */
	public GpGcjsXmjlId(String id) {
		this.id = id;
	}

	/** full constructor */
	public GpGcjsXmjlId(String id, String name, String phone, String zzName,
			String zzCode, String note) {
		this.id = id;
		this.name = name;
		this.phone = phone;
		this.zzName = zzName;
		this.zzCode = zzCode;
		this.note = note;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getZzName() {
		return this.zzName;
	}

	public void setZzName(String zzName) {
		this.zzName = zzName;
	}

	public String getZzCode() {
		return this.zzCode;
	}

	public void setZzCode(String zzCode) {
		this.zzCode = zzCode;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GpGcjsXmjlId))
			return false;
		GpGcjsXmjlId castOther = (GpGcjsXmjlId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& ((this.getPhone() == castOther.getPhone()) || (this
						.getPhone() != null
						&& castOther.getPhone() != null && this.getPhone()
						.equals(castOther.getPhone())))
				&& ((this.getZzName() == castOther.getZzName()) || (this
						.getZzName() != null
						&& castOther.getZzName() != null && this.getZzName()
						.equals(castOther.getZzName())))
				&& ((this.getZzCode() == castOther.getZzCode()) || (this
						.getZzCode() != null
						&& castOther.getZzCode() != null && this.getZzCode()
						.equals(castOther.getZzCode())))
				&& ((this.getNote() == castOther.getNote()) || (this.getNote() != null
						&& castOther.getNote() != null && this.getNote()
						.equals(castOther.getNote())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result
				+ (getPhone() == null ? 0 : this.getPhone().hashCode());
		result = 37 * result
				+ (getZzName() == null ? 0 : this.getZzName().hashCode());
		result = 37 * result
				+ (getZzCode() == null ? 0 : this.getZzCode().hashCode());
		result = 37 * result
				+ (getNote() == null ? 0 : this.getNote().hashCode());
		return result;
	}

}