package bo;

import java.util.Date;

/**
 * GpJsgcExpAssessId generated by MyEclipse Persistence Tools
 */

public class GpJsgcExpAssessId implements java.io.Serializable {

	// Fields

	private String expId;

	private String id;

	private String projId;

	private String expName;

	private Double score1;

	private Double score2;

	private Double score3;

	private Double score4;

	private Double score5;

	private Double score6;

	private Double score7;

	private Double score8;

	private Double score9;

	private Double score10;

	private Double sumScore;

	private String koufenNote;

	private String opertor;

	private Date opTime;

	// Constructors

	/** default constructor */
	public GpJsgcExpAssessId() {
	}

	/** minimal constructor */
	public GpJsgcExpAssessId(String id) {
		this.id = id;
	}

	/** full constructor */
	public GpJsgcExpAssessId(String expId, String id, String projId,
			String expName, Double score1, Double score2, Double score3,
			Double score4, Double score5, Double score6, Double score7,
			Double score8, Double score9, Double score10, Double sumScore,
			String koufenNote, String opertor, Date opTime) {
		this.expId = expId;
		this.id = id;
		this.projId = projId;
		this.expName = expName;
		this.score1 = score1;
		this.score2 = score2;
		this.score3 = score3;
		this.score4 = score4;
		this.score5 = score5;
		this.score6 = score6;
		this.score7 = score7;
		this.score8 = score8;
		this.score9 = score9;
		this.score10 = score10;
		this.sumScore = sumScore;
		this.koufenNote = koufenNote;
		this.opertor = opertor;
		this.opTime = opTime;
	}

	// Property accessors

	public String getExpId() {
		return this.expId;
	}

	public void setExpId(String expId) {
		this.expId = expId;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getProjId() {
		return this.projId;
	}

	public void setProjId(String projId) {
		this.projId = projId;
	}

	public String getExpName() {
		return this.expName;
	}

	public void setExpName(String expName) {
		this.expName = expName;
	}

	public Double getScore1() {
		return this.score1;
	}

	public void setScore1(Double score1) {
		this.score1 = score1;
	}

	public Double getScore2() {
		return this.score2;
	}

	public void setScore2(Double score2) {
		this.score2 = score2;
	}

	public Double getScore3() {
		return this.score3;
	}

	public void setScore3(Double score3) {
		this.score3 = score3;
	}

	public Double getScore4() {
		return this.score4;
	}

	public void setScore4(Double score4) {
		this.score4 = score4;
	}

	public Double getScore5() {
		return this.score5;
	}

	public void setScore5(Double score5) {
		this.score5 = score5;
	}

	public Double getScore6() {
		return this.score6;
	}

	public void setScore6(Double score6) {
		this.score6 = score6;
	}

	public Double getScore7() {
		return this.score7;
	}

	public void setScore7(Double score7) {
		this.score7 = score7;
	}

	public Double getScore8() {
		return this.score8;
	}

	public void setScore8(Double score8) {
		this.score8 = score8;
	}

	public Double getScore9() {
		return this.score9;
	}

	public void setScore9(Double score9) {
		this.score9 = score9;
	}

	public Double getScore10() {
		return this.score10;
	}

	public void setScore10(Double score10) {
		this.score10 = score10;
	}

	public Double getSumScore() {
		return this.sumScore;
	}

	public void setSumScore(Double sumScore) {
		this.sumScore = sumScore;
	}

	public String getKoufenNote() {
		return this.koufenNote;
	}

	public void setKoufenNote(String koufenNote) {
		this.koufenNote = koufenNote;
	}

	public String getOpertor() {
		return this.opertor;
	}

	public void setOpertor(String opertor) {
		this.opertor = opertor;
	}

	public Date getOpTime() {
		return this.opTime;
	}

	public void setOpTime(Date opTime) {
		this.opTime = opTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GpJsgcExpAssessId))
			return false;
		GpJsgcExpAssessId castOther = (GpJsgcExpAssessId) other;

		return ((this.getExpId() == castOther.getExpId()) || (this.getExpId() != null
				&& castOther.getExpId() != null && this.getExpId().equals(
				castOther.getExpId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getProjId() == castOther.getProjId()) || (this
						.getProjId() != null
						&& castOther.getProjId() != null && this.getProjId()
						.equals(castOther.getProjId())))
				&& ((this.getExpName() == castOther.getExpName()) || (this
						.getExpName() != null
						&& castOther.getExpName() != null && this.getExpName()
						.equals(castOther.getExpName())))
				&& ((this.getScore1() == castOther.getScore1()) || (this
						.getScore1() != null
						&& castOther.getScore1() != null && this.getScore1()
						.equals(castOther.getScore1())))
				&& ((this.getScore2() == castOther.getScore2()) || (this
						.getScore2() != null
						&& castOther.getScore2() != null && this.getScore2()
						.equals(castOther.getScore2())))
				&& ((this.getScore3() == castOther.getScore3()) || (this
						.getScore3() != null
						&& castOther.getScore3() != null && this.getScore3()
						.equals(castOther.getScore3())))
				&& ((this.getScore4() == castOther.getScore4()) || (this
						.getScore4() != null
						&& castOther.getScore4() != null && this.getScore4()
						.equals(castOther.getScore4())))
				&& ((this.getScore5() == castOther.getScore5()) || (this
						.getScore5() != null
						&& castOther.getScore5() != null && this.getScore5()
						.equals(castOther.getScore5())))
				&& ((this.getScore6() == castOther.getScore6()) || (this
						.getScore6() != null
						&& castOther.getScore6() != null && this.getScore6()
						.equals(castOther.getScore6())))
				&& ((this.getScore7() == castOther.getScore7()) || (this
						.getScore7() != null
						&& castOther.getScore7() != null && this.getScore7()
						.equals(castOther.getScore7())))
				&& ((this.getScore8() == castOther.getScore8()) || (this
						.getScore8() != null
						&& castOther.getScore8() != null && this.getScore8()
						.equals(castOther.getScore8())))
				&& ((this.getScore9() == castOther.getScore9()) || (this
						.getScore9() != null
						&& castOther.getScore9() != null && this.getScore9()
						.equals(castOther.getScore9())))
				&& ((this.getScore10() == castOther.getScore10()) || (this
						.getScore10() != null
						&& castOther.getScore10() != null && this.getScore10()
						.equals(castOther.getScore10())))
				&& ((this.getSumScore() == castOther.getSumScore()) || (this
						.getSumScore() != null
						&& castOther.getSumScore() != null && this
						.getSumScore().equals(castOther.getSumScore())))
				&& ((this.getKoufenNote() == castOther.getKoufenNote()) || (this
						.getKoufenNote() != null
						&& castOther.getKoufenNote() != null && this
						.getKoufenNote().equals(castOther.getKoufenNote())))
				&& ((this.getOpertor() == castOther.getOpertor()) || (this
						.getOpertor() != null
						&& castOther.getOpertor() != null && this.getOpertor()
						.equals(castOther.getOpertor())))
				&& ((this.getOpTime() == castOther.getOpTime()) || (this
						.getOpTime() != null
						&& castOther.getOpTime() != null && this.getOpTime()
						.equals(castOther.getOpTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getExpId() == null ? 0 : this.getExpId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getProjId() == null ? 0 : this.getProjId().hashCode());
		result = 37 * result
				+ (getExpName() == null ? 0 : this.getExpName().hashCode());
		result = 37 * result
				+ (getScore1() == null ? 0 : this.getScore1().hashCode());
		result = 37 * result
				+ (getScore2() == null ? 0 : this.getScore2().hashCode());
		result = 37 * result
				+ (getScore3() == null ? 0 : this.getScore3().hashCode());
		result = 37 * result
				+ (getScore4() == null ? 0 : this.getScore4().hashCode());
		result = 37 * result
				+ (getScore5() == null ? 0 : this.getScore5().hashCode());
		result = 37 * result
				+ (getScore6() == null ? 0 : this.getScore6().hashCode());
		result = 37 * result
				+ (getScore7() == null ? 0 : this.getScore7().hashCode());
		result = 37 * result
				+ (getScore8() == null ? 0 : this.getScore8().hashCode());
		result = 37 * result
				+ (getScore9() == null ? 0 : this.getScore9().hashCode());
		result = 37 * result
				+ (getScore10() == null ? 0 : this.getScore10().hashCode());
		result = 37 * result
				+ (getSumScore() == null ? 0 : this.getSumScore().hashCode());
		result = 37
				* result
				+ (getKoufenNote() == null ? 0 : this.getKoufenNote()
						.hashCode());
		result = 37 * result
				+ (getOpertor() == null ? 0 : this.getOpertor().hashCode());
		result = 37 * result
				+ (getOpTime() == null ? 0 : this.getOpTime().hashCode());
		return result;
	}

}