package bo;

/**
 * GpJsgcExpCard generated by MyEclipse Persistence Tools
 */

public class GpJsgcExpCard implements java.io.Serializable {

	// Fields

	private GpJsgcExpCardId id;

	// Constructors

	/** default constructor */
	public GpJsgcExpCard() {
	}

	/** full constructor */
	public GpJsgcExpCard(GpJsgcExpCardId id) {
		this.id = id;
	}

	// Property accessors

	public GpJsgcExpCardId getId() {
		return this.id;
	}

	public void setId(GpJsgcExpCardId id) {
		this.id = id;
	}

}