package bo;

/**
 * GpJsgcExpSign generated by MyEclipse Persistence Tools
 */

public class GpJsgcExpSign implements java.io.Serializable {

	// Fields

	private GpJsgcExpSignId id;

	// Constructors

	/** default constructor */
	public GpJsgcExpSign() {
	}

	/** full constructor */
	public GpJsgcExpSign(GpJsgcExpSignId id) {
		this.id = id;
	}

	// Property accessors

	public GpJsgcExpSignId getId() {
		return this.id;
	}

	public void setId(GpJsgcExpSignId id) {
		this.id = id;
	}

}