package bo;

import java.util.Date;

/**
 * GpJsgcExpCardId generated by MyEclipse Persistence Tools
 */

public class GpJsgcExpCardId implements java.io.Serializable {

	// Fields

	private String id;

	private String cardNo;

	private String expName;

	private Date slotcardTime;

	// Constructors

	/** default constructor */
	public GpJsgcExpCardId() {
	}

	/** minimal constructor */
	public GpJsgcExpCardId(String id) {
		this.id = id;
	}

	/** full constructor */
	public GpJsgcExpCardId(String id, String cardNo, String expName,
			Date slotcardTime) {
		this.id = id;
		this.cardNo = cardNo;
		this.expName = expName;
		this.slotcardTime = slotcardTime;
	}

	// Property accessors

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getCardNo() {
		return this.cardNo;
	}

	public void setCardNo(String cardNo) {
		this.cardNo = cardNo;
	}

	public String getExpName() {
		return this.expName;
	}

	public void setExpName(String expName) {
		this.expName = expName;
	}

	public Date getSlotcardTime() {
		return this.slotcardTime;
	}

	public void setSlotcardTime(Date slotcardTime) {
		this.slotcardTime = slotcardTime;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof GpJsgcExpCardId))
			return false;
		GpJsgcExpCardId castOther = (GpJsgcExpCardId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getCardNo() == castOther.getCardNo()) || (this
						.getCardNo() != null
						&& castOther.getCardNo() != null && this.getCardNo()
						.equals(castOther.getCardNo())))
				&& ((this.getExpName() == castOther.getExpName()) || (this
						.getExpName() != null
						&& castOther.getExpName() != null && this.getExpName()
						.equals(castOther.getExpName())))
				&& ((this.getSlotcardTime() == castOther.getSlotcardTime()) || (this
						.getSlotcardTime() != null
						&& castOther.getSlotcardTime() != null && this
						.getSlotcardTime().equals(castOther.getSlotcardTime())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getCardNo() == null ? 0 : this.getCardNo().hashCode());
		result = 37 * result
				+ (getExpName() == null ? 0 : this.getExpName().hashCode());
		result = 37
				* result
				+ (getSlotcardTime() == null ? 0 : this.getSlotcardTime()
						.hashCode());
		return result;
	}

}