package bo;

/**
 * GpJsgcExpAssess generated by MyEclipse Persistence Tools
 */

public class GpJsgcExpAssess implements java.io.Serializable {

	// Fields

	private GpJsgcExpAssessId id;

	// Constructors

	/** default constructor */
	public GpJsgcExpAssess() {
	}

	/** full constructor */
	public GpJsgcExpAssess(GpJsgcExpAssessId id) {
		this.id = id;
	}

	// Property accessors

	public GpJsgcExpAssessId getId() {
		return this.id;
	}

	public void setId(GpJsgcExpAssessId id) {
		this.id = id;
	}

}